### ISSUE TITLE
Is there a way to add more than one toaster stack instances?

### ISSUE THREAD

**Issue by bradyclifford** [tameraydin/ngToast#32]
I would like have a toaster for the main spa but also utilize it in a child view.  Can I create multiple toaster stack instances?

**Comment by tameraydin** [comment]
I think it is not possible to have multiple stack instances since providers are singletons. 

But it might still be possible to have multiple toast containers (the directive) that are able to display specific toast messages, by using CSS. Please check the following out:
http://plnkr.co/edit/P4WN0DGNh3kaSOJCpcdK?p=preview

**Comment by bradyclifford** [comment]
Perfect! That will work. Thanks.
