### ISSUE TITLE
wrong position

### ISSUE THREAD

**Issue by salkat** [tameraydin/ngToast#37]
I use code

ngToast.create({
	content: 'Телефонный канал подключен',
	horizontalPosition: "left"
});

and can see small part of Toast at the top right of screen as you can seen on screenshot
![2015-04-14 11 06 44](https://cloud.githubusercontent.com/assets/6958630/7132918/6607ed4a-e296-11e4-9bb6-ac86746d978a.png)

with any horizontalPosition setting: left, right or center
MacOS, latest Firefox, Opera, Chrome

**Comment by tameraydin** [comment]
You cannot set **horizontalPosition** option within ``create()``, it needs to be set on configuration level. Please check [this](https://github.com/tameraydin/ngToast/issues/10#issuecomment-64061276) out.

**Comment by ayanth** [comment]
I get this issue when its set on 'right':
https://i.gyazo.com/e92641b6bff1f90effba24b5b133fe21.png

'left' is perfect tho, well aligned with the bootstrap content div:
https://i.gyazo.com/14777be29f9816abe96ca29cecf2228c.png

```
ngToastProvider.configure({
		animation: 'slide',
		verticalPosition: 'top',
		horizontalPosition: 'right'
	})
```

I have tried putting it in bootstrap's row&col-xs-12. Still out of content.

**Comment by stormmuller** [comment]
I was facing this issue.

In my particular case, the issue was that the toast was being rendered inside a div with the bootstrap class "container". I assume this might happen when placing the <toast> tag in other types of containers as well. 

Moved the <toast> tag out of the container and put it directly into the body. And it worked like a charm.

If you applied the container tag to the body you're probably out of luck unless you're prepared to refactor the HTML structure or fork the toast library to fix the issue. No idea why this was closed without a proper fix or explanation.
